name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
       - name: Run tests
         run: bundle exec rake test
       - name: Run tests with coverage
         run: bundle exec rake coverage
       - name: Run RuboCop
         run: bundle exec rubocop --except Metrics

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Run full RuboCop
        run: bundle exec rubocop
       - name: Generate YARD documentation
         run: bundle exec yard doc --fail-on-warning
       - name: Check documentation coverage
         run: bundle exec yard stats --list-undoc
       - name: Run security audit
         run: bundle exec rake audit
